### ISSUE TITLE
Le protocole n'est pas conservé dans les URL

### ISSUE THREAD

**Issue by taophp** [humboldtux/asciidoctor-diamonded#1]
Le protocole n'est pas conservé lorsqu'une url est détectée. C'est déjà gênant dans le texte (si je précise le protocole, c'est que j'ai une raison, sinon je ne m'amuserai pas à taper tous ces http://, https:// et autres ftp:// pour le plaisir), mais c'est carrément problématique lorsqu'il s'agit de blocs de code ou console. En effet, la ligne :

```
git clone https://github.com/fkooman/php-remote-storage.git
```

devient :

```
git clone github.com/fkooman/php-remote-storage.git
```
ce qui est incorrect et risque d'induire des lecteurs en erreur.

**Comment by humboldtux** [comment]
J'ai commité des modifs, dis-moi si ça corrige ton problème.

**Comment by taophp** [comment]
Oui, c'est bon. Merci.
